-- Import existing local data.js references into Supabase.
-- Run this once in the Supabase SQL Editor after supabase-schema.sql.
-- Existing rows with the same image/source/title are skipped.

begin;

create unique index if not exists references_unique_item
on public.references (image, (coalesce(source, '')), title);

insert into public.tag_groups (group_name, tags, sort_order)
values
  ('Author', array['vaccaro-giuseppe', 'sauerbruch-hutton', 'mosso-nicola-leonardo', 'christ-gantenbein', 'smithson-alison-peter', 'mies-van-der-rohe-ludwig', 'loos-adolf', 'kerez-christian', 'zumthor-peter', 'dorval-bory-nicolas', 'archigram', 'libera-adalberto', 'deplazes-bearth', 'rogers-richard', 'r-architecture', 'vernacular', 'bruther', 'baukunst', 'enzmann-fischer-partner', 'buchner-bruendler', 'olgiati-valerio', 'maerkli-peter', 'lacaton-vassal', 'matta-clark-gordon', 'matte-trucco', 'piano-renzo', 'de-vylder-vinck-taillieu', 'tschumi-bernard', 'exner-inger-johannes', '127af', 'le-corbusier', 'herbst-rene']::text[], 0),
  ('Location', array['france', 'uk', 'italy', 'usa', 'germany', 'denmark', 'belgium', 'switzerland', 'paris', 'berlin', 'vienna', 'zurich', 'bordeaux', 'prague', 'basel', 'turin', 'coast', 'mountains', 'desert', 'forest']::text[], 1),
  ('Typology', array['church', 'extension', 'student-housing', 'parking', 'alternative-living', 'mixed-use', 'office', 'house', 'social-housing', 'housing', 'factory', 'museum', 'park', 'pavilion', 'kindergarten', 'tower', 'cabin']::text[], 2),
  ('Elements', array['bathroom', 'bedroom', 'carpet', 'curtain', 'staircase', 'handrail', 'oculus', 'elevated', 'dome', 'bracing', 'pipes', 'electricity', 'building-services', 'slabs', 'gallery', 'hall', 'interior', 'laubengang', 'porch', 'transformation', 'balcony', 'ramp', 'roof', 'facade', 'columns', 'courtyard', 'structure', 'door', 'window', 'ceiling', 'floor', 'wall', 'corridor', 'lobby', 'atrium', 'terrace', 'garden', 'garage', 'basement', 'attic', 'elevator', 'escalator', 'beam', 'pillar', 'foundation', 'canopy', 'skylight', 'partition', 'furniture', 'lighting', 'spiral-stair', 'stair', 'sink', 'detail']::text[], 3),
  ('Material', array['concrete', 'textile', 'glass-bricks', 'corrugated-something', 'chain-link-fence', 'net', 'sand', 'earth', 'plaster', 'stone', 'glass', 'brick', 'clay', 'adobe', 'bamboo', 'thatch', 'straw', 'gravel', 'limestone', 'marble', 'granite', 'slate', 'asphalt', 'tar', 'resin', 'fiberglass', 'carbon-fiber', 'plastic', 'polycarbonate', 'ceramic', 'tile', 'gypsum', 'chalk', 'cork', 'rubber', 'felt', 'wool', 'wood', 'metal']::text[], 4),
  ('Wer hats mir gezeigt?', array['gta', 'ich-war-da', 'self-photographed']::text[], 5),
  ('Style', array['brutalism', 'cubic', 'tensioned', 'membran', 'contemporary', 'industrial']::text[], 6),
  ('Form', array['circular', 'triangular', 'monolithic', 'organic', 'geometric', 'symmetrical']::text[], 7),
  ('Color', array['colorful', 'grey', 'red', 'orange', 'blue', 'yellow', 'green', 'black', 'white', 'reflective']::text[], 8),
  ('Other', array['representation', 'in-noisy-places', 'concept', 'circulation', 'experimental', 'self-built', 'temporary']::text[], 9)
on conflict (group_name)
do update set
  tags = (
    select array_agg(distinct tag order by tag)
    from unnest(public.tag_groups.tags || excluded.tags) as tag
  ),
  sort_order = excluded.sort_order;

update public.tag_groups
set tags = array_remove(tags, 'interior')
where group_name = 'Typology';

update public.tag_groups
set tags = array_remove(tags, 'extension')
where group_name = 'Elements';

update public.tag_groups
set tags = (
  select array_agg(distinct tag order by tag)
  from unnest(public.tag_groups.tags) as tag
)
where tags is not null;

insert into public.references (image, source, title, tags, status)
values
  ('https://www.sauerbruchhutton.de/cache/images/media/projekte/l57.h6/1400-h6_d_4142_janbitter.jpg', 'https://www.sauerbruchhutton.de/de/project/l57-h6', 'Sauerbruch Hutton  —  Haus 6 Berlin', array['berlin', 'germany', 'housing', 'facade', 'metal', 'reflective', 'sauerbruch-hutton']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1478527437/emnt8ium9hwrzkdcw2x3/nicola-mosso-leonardo-mosso-federico-padovani-chiesa-del-gesu-redentore.jpg', 'https://divisare.com/projects/329902-leonardo-mosso-nicola-mosso-federico-padovani-chiesa-del-gesu-redentore', 'Nicola Mosso + Leonardo Mosso  —  Chiesa del Gesù Redentore', array['italy', 'turin', 'church', 'brick', 'brutalism', 'facade', 'detail', 'mosso-nicola-leonardo']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1478527445/b2ctbirate60nsmbkgga/nicola-mosso-leonardo-mosso-federico-padovani-chiesa-del-gesu-redentore.jpg', 'https://divisare.com/projects/329902-leonardo-mosso-nicola-mosso-federico-padovani-chiesa-del-gesu-redentore', 'Nicola Mosso + Leonardo Mosso  —  Chiesa del Gesù Redentore', array['italy', 'turin', 'church', 'structure', 'brick', 'concrete', 'brutalism', 'triangular', 'symmetrical', 'geometric', 'roof', 'window', 'mosso-nicola-leonardo']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1478527404/r2dnb365wss6gfjgltfx/nicola-mosso-leonardo-mosso-federico-padovani-chiesa-del-gesu-redentore.jpg', 'https://divisare.com/projects/329902-leonardo-mosso-nicola-mosso-federico-padovani-chiesa-del-gesu-redentore', 'Nicola Mosso + Leonardo Mosso  —  Chiesa del Gesù Redentore', array['italy', 'turin', 'church', 'structure', 'ceiling', 'brick', 'concrete', 'brutalism', 'triangular', 'symmetrical', 'geometric', 'mosso-nicola-leonardo']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1456844904/gun0sxfucdwbuavo59fv/christ-gantenbein-radu-malasincu-stefano-graziani-kunstmuseum-basel.jpg', 'https://divisare.com/projects/311763-christ-gantenbein-stefano-graziani-radu-malasincu-kunstmuseum-basel', 'Christ & Gantenbein  —  Kunstmuseum Basel', array['basel', 'switzerland', 'museum', 'brick', 'facade', 'door', 'metal', 'christ-gantenbein', 'grey']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1465546421/u3qnbahzyzsdxfhms4vp/christ-gantenbein-radu-malasincu-stefano-graziani-kunstmuseum-basel.jpg', 'https://divisare.com/projects/311763-christ-gantenbein-stefano-graziani-radu-malasincu-kunstmuseum-basel', 'Christ & Gantenbein  —  Kunstmuseum Basel', array['basel', 'switzerland', 'museum', 'brick', 'stone', 'concrete', 'skylight', 'lighting', 'christ-gantenbein', 'grey']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1465546430/snfrq8mc8yl8k6najh5q/christ-gantenbein-radu-malasincu-stefano-graziani-kunstmuseum-basel.jpg', 'https://divisare.com/projects/311763-christ-gantenbein-stefano-graziani-radu-malasincu-kunstmuseum-basel', 'Christ & Gantenbein  —  Kunstmuseum Basel', array['basel', 'switzerland', 'museum', 'brick', 'stair', 'staircase', 'stone', 'concrete', 'christ-gantenbein', 'grey']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1465546403/ofdzzkd2aigomuilcudf/christ-gantenbein-radu-malasincu-stefano-graziani-kunstmuseum-basel.jpg', 'https://divisare.com/projects/311763-christ-gantenbein-stefano-graziani-radu-malasincu-kunstmuseum-basel', 'Christ & Gantenbein  —  Kunstmuseum Basel', array['basel', 'switzerland', 'atrium', 'museum', 'brick', 'stair', 'staircase', 'stone', 'concrete', 'christ-gantenbein', 'grey']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1465546408/xfx3ozrlblbojv6dk22l/christ-gantenbein-radu-malasincu-stefano-graziani-kunstmuseum-basel.jpg', 'https://divisare.com/projects/311763-christ-gantenbein-stefano-graziani-radu-malasincu-kunstmuseum-basel', 'Christ & Gantenbein  —  Kunstmuseum Basel', array['basel', 'switzerland', 'museum', 'brick', 'facade', 'christ-gantenbein', 'extension', 'grey']::text[], 'approved'),
  ('https://architecture-history.org/architects/architects/SMITHSON/PIC/PV06.png', 'https://architecture-history.org/architects/architects/SMITHSON/OBJ/1970,%20Garden%20Building,%20St.%20Hilda%27s%20College,%20Oxford,%20UK.html', 'Peter Smithson + Alison Smithson  —  Garden Building St. Hilda''s College Oxford', array['student-housing', 'structure', 'facade', 'wood', 'glass', 'concrete', 'detail', 'brutalism', 'geometric', 'bracing', 'smithson-alison-peter', 'uk']::text[], 'approved'),
  ('https://architecture-history.org/architects/architects/SMITHSON/PIC/PV02.png', 'https://architecture-history.org/architects/architects/SMITHSON/OBJ/1970,%20Garden%20Building,%20St.%20Hilda%27s%20College,%20Oxford,%20UK.html', 'Peter Smithson + Alison Smithson  —  Garden Building St. Hilda''s College Oxford', array['student-housing', 'facade', 'structure', 'concrete', 'wood', 'glass', 'brutalism', 'smithson-alison-peter', 'bracing', 'uk']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1522162505/shnjhitmw6y50qseefhr/ludwig-mies-van-der-rohe-rory-gardiner-neue-nationalgalerie.jpg', 'https://divisare.com/projects/297030-ludwig-mies-van-der-rohe-rory-gardiner-neue-nationalgalerie', 'Ludwig Mies van der Rohe  —  Neue Nationalgalerie Berlin', array['germany', 'berlin', 'museum', 'structure', 'columns', 'ceiling', 'ich-war-da', 'metal', 'glass', 'marble', 'mies-van-der-rohe-ludwig']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1460372607/fhtfpwjnphnzofxm1vyq/ludwig-mies-van-der-rohe-rory-gardiner-neue-nationalgalerie.jpg', 'https://divisare.com/projects/297030-ludwig-mies-van-der-rohe-rory-gardiner-neue-nationalgalerie', 'Ludwig Mies van der Rohe  —  Neue Nationalgalerie Berlin', array['germany', 'berlin', 'museum', 'metal', 'glass', 'structure', 'columns', 'facade', 'roof', 'ceiling', 'ich-war-da', 'mies-van-der-rohe-ludwig']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1460372607/szpbeiasdltoezqzkoqt/ludwig-mies-van-der-rohe-rory-gardiner-neue-nationalgalerie.jpg', 'https://divisare.com/projects/297030-ludwig-mies-van-der-rohe-rory-gardiner-neue-nationalgalerie', 'Ludwig Mies van der Rohe  —  Neue Nationalgalerie Berlin', array['germany', 'museum', 'roof', 'metal', 'glass', 'mies-van-der-rohe-ludwig', 'ich-war-da', 'berlin']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1449763477/ljxkfz0slyt6jkxxcawy/adolf-loos-hubmann-vass-architekten-we-will-remake-this-on-the-reconstruction-of-a-manifesto-lina-and-adolf-loos-bedroom.jpg', 'https://divisare.com/projects/305298-adolf-loos-hubmann-vass-architekten-we-will-remake-this-on-the-reconstruction-of-a-manifesto-lina-and-adolf-loos-bedroom', 'Adolf Loos  —  Bedroom for Lina', array['white', 'cubic', 'loos-adolf', 'vienna', 'interior', 'bedroom', 'carpet', 'curtain', 'textile']::text[], 'approved'),
  ('https://afasiaarchzine.com/wp-content/uploads/2024/04/Christian-Kerez-.-House-Okamura-.-Prague-afasia-1.jpg', 'https://afasiaarchzine.com/2025/02/christian-kerez-house-okamura-prague/', 'Christian Kerez  —  House Okamura Prague', array['brick', 'house', 'facade', 'circular', 'geometric', 'kerez-christian', 'prague']::text[], 'approved'),
  ('https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj53aiWs_KRJOtSYvSIrJKxa1rru7GhDKZem97EtJFsi0KHDzCT_mRRjVyx30mBHIr0nHcV5iGjcj30X_uYBY6jNIF_1l6im93GmHao9TVFt1jpdNkiGkVYbwGU3DO_FqIuuMrBr-JKujjWA2OfC1heH9HfTBG155SfH2adhvCD8vLfZjm-yrEhl8eOPROe/s640/SchemesForTheInterior%20Spaces.gif', 'https://afasiaarchzine.com/2025/02/christian-kerez-house-okamura-prague/', 'Christian Kerez  —  House Okamura Prague', array['house', 'circular', 'geometric', 'spiral-stair', 'circulation', 'concept', 'kerez-christian', 'prague']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1540757722/yqw2dugrsjqcgt7pt6ur/peter-zumthor-august-fischer-caplutta-sogn-benedetg.jpg', 'https://divisare.com/projects/399322-peter-zumthor-august-fischer-caplutta-sogn-benedetg', 'Peter Zumthor  —  Caplutta Sogn Benedetg Sumvitg', array['mountains', 'switzerland', 'church', 'wood', 'gta', 'ich-war-da', 'window', 'floor', 'beam', 'furniture', 'hall', 'ceiling', 'symmetrical', 'zumthor-peter']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1540757732/ytapdpqzdujh1exgavgi/peter-zumthor-august-fischer-caplutta-sogn-benedetg.jpg', 'https://divisare.com/projects/399322-peter-zumthor-august-fischer-caplutta-sogn-benedetg', 'Peter Zumthor  —  Caplutta Sogn Benedetg Sumvitg', array['mountains', 'switzerland', 'church', 'facade', 'wood', 'gta', 'ich-war-da', 'window', 'stair', 'concrete', 'zumthor-peter', 'handrail']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1540757721/cv2xvdcc2m581fb4e9ma/peter-zumthor-august-fischer-caplutta-sogn-benedetg.jpg', 'https://divisare.com/projects/399322-peter-zumthor-august-fischer-caplutta-sogn-benedet', 'Peter Zumthor  —  Caplutta Sogn Benedetg Sumvitg', array['mountains', 'switzerland', 'church', 'roof', 'facade', 'wood', 'gta', 'ich-war-da', 'window', 'zumthor-peter']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1500971150/rfk0g4ut0prfvogw5b1q/peter-zumthor-rasmus-hjortshoj-coast-bruder-klaus-feldkapelle.jpg', 'https://divisare.com/projects/349303-peter-zumthor-rasmus-hjortshoj-bruder-klaus-feldkapelle', 'Peter Zumthor  —  Bruder Klaus Field Chapel Mechernich', array['germany', 'concrete', 'geometric', 'black', 'door', 'metal', 'zumthor-peter', 'triangular']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1500971153/vihwbwlyywd8sgwdobze/peter-zumthor-rasmus-hjortshoj-coast-bruder-klaus-feldkapelle.jpg', 'https://divisare.com/projects/349303-peter-zumthor-rasmus-hjortshoj-bruder-klaus-feldkapelle', 'Peter Zumthor  —  Bruder Klaus Field Chapel Mechernich', array['germany', 'church', 'concrete', 'geometric', 'black', 'zumthor-peter', 'monolithic', 'oculus']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1500971149/m1rf6rblzzleoou1txns/peter-zumthor-rasmus-hjortshoj-coast-bruder-klaus-feldkapelle.jpg', 'https://divisare.com/projects/349303-peter-zumthor-rasmus-hjortshoj-bruder-klaus-feldkapelle', 'Peter Zumthor  —  Bruder Klaus Field Chapel Mechernich', array['germany', 'church', 'concrete', 'geometric', 'zumthor-peter', 'monolithic']::text[], 'approved'),
  ('http://www.nicolasdorvalbory.fr/content/1-home/nicolasdorvalbory_treehouse_dscf5131-ok.jpg', 'http://www.nicolasdorvalbory.fr/project:treehouse', 'Nicolas Dorval-Bory  —  Self Built Treehouse', array['france', 'elevated', 'cabin', 'wood', 'structure', 'foundation', 'beam', 'columns', 'dorval-bory-nicolas', 'bracing', 'forest']::text[], 'approved'),
  ('http://www.nicolasdorvalbory.fr/content/1-home/nicolasdorvalbory_treehouse_dscf5103-ok.jpg', 'http://www.nicolasdorvalbory.fr/project:treehouse', 'Nicolas Dorval-Bory  —  Self Built Treehouse', array['france', 'cabin', 'roof', 'window', 'geometric', 'wood', 'black', 'skylight', 'glass', 'fiberglass', 'circular', 'dorval-bory-nicolas', 'forest']::text[], 'approved'),
  ('http://www.nicolasdorvalbory.fr/content/1-home/nicolasdorvalbory_treehouse_dscf5092.jpg', 'http://www.nicolasdorvalbory.fr/project:treehouse', 'Nicolas Dorval-Bory  —  Self Built Treehouse', array['france', 'cabin', 'facade', 'roof', 'window', 'geometric', 'wood', 'black', 'dorval-bory-nicolas', 'forest']::text[], 'approved'),
  ('https://64.media.tumblr.com/0020542db89643cddf592a4df8f4febd/tumblr_nzieh9fqnL1twhq1io6_1280.jpg', 'http://www.nicolasdorvalbory.fr/project:treehouse', 'Jean-Philippe Vassal  —  Vassal House (Paillote) Niamey', array['alternative-living', 'desert', 'pavilion', 'roof', 'structure', 'thatch', 'lacaton-vassal', 'sand', 'wood', 'straw', 'circular', 'niger']::text[], 'approved'),
  ('https://static.wixstatic.com/media/a77b8c_775999ed2ca5e158244dd76600a6e532.png/v1/fill/w_689,h_1253,al_c,q_90,enc_avif,quality_auto/a77b8c_775999ed2ca5e158244dd76600a6e532.png', 'https://www.dropcitydoc.com/about', 'Archigram  —  Drop City USA', array['alternative-living', 'desert', 'archigram', 'structure', 'geometric', 'concept', 'wood', 'usa', 'dome', 'experimental', 'self-built', 'temporary']::text[], 'approved'),
  ('https://arte-util.org/cms/wp-content/uploads/2013/12/056-drop-city-01-1590x1060.jpg', 'https://arte-util.org/projects/drop-city/', 'Archigram  —  Drop City USA', array['alternative-living', 'structure', 'archigram', 'roof', 'desert', 'geometric', 'concept', 'usa', 'dome', 'experimental', 'self-built', 'temporary']::text[], 'approved'),
  ('https://primary.jwwb.nl/public/m/c/b/temp-gwewjpsuastlshqtpqee/image-high-ttcmh8.png?enable-io=true&crop=1.4369%3A1&width=1920', 'https://www.philologus.eu/kunst/villa-malaparte-capri', 'Adalberto Libera  —  Villa Malaparte Capri', array['italy', 'coast', 'house', 'geometric', 'plaster', 'wood', 'window', 'wall', 'libera-adalberto']::text[], 'approved'),
  ('https://primary.jwwb.nl/public/m/c/b/temp-gwewjpsuastlshqtpqee/s309sy/image-142.png?enable-io=true&width=1920', 'https://www.philologus.eu/kunst/villa-malaparte-capri', 'Adalberto Libera  —  Villa Malaparte Capri', array['italy', 'coast', 'house', 'brick', 'stone', 'geometric', 'red', 'roof', 'facade', 'stair', 'libera-adalberto', 'cubic']::text[], 'approved'),
  ('https://cdn.archilovers.com/projects/b_730_2aec3267-143c-43d1-9fc9-a665dbf1bb0a.jpg', 'https://www.archilovers.com/projects/12125/new-monte-rosa-hut.html', 'Bearth & Deplazes  —  Monte Rosa Hütte', array['mountains', 'switzerland', 'cabin', 'geometric', 'columns', 'interior', 'furniture', 'wood', 'deplazes-bearth']::text[], 'approved'),
  ('https://cdn.archilovers.com/projects/b_730_933d5e9b-d60c-44cb-bfb3-47cf428d58d8.jpg', 'https://www.archilovers.com/projects/12125/new-monte-rosa-hut.html', 'Bearth & Deplazes  —  Monte Rosa Hütte', array['mountains', 'switzerland', 'cabin', 'facade', 'roof', 'structure', 'metal', 'geometric', 'deplazes-bearth', 'reflective']::text[], 'approved'),
  ('https://www.centrepompidou.fr/fileadmin/_processed_/2/b/csm_dossier_architecture-centre-pompidou_visibilite-4-3-jaune_1ccb89aef3.jpg', 'https://www.centrepompidou.fr/fr/offre-aux-professionnels/enseignants/dossiers-ressources-sur-lart/larchitecture-du-centre-pompidou/image-et-identite', 'Renzo Piano + Richard Rogers  —  Centre Pompidou Paris,  Le jaune pour l''électricité', array['france', 'piano-renzo', 'paris', 'museum', 'metal', 'ich-war-da', 'yellow', 'concept', 'green', 'rogers-richard', 'building-services', 'electricity']::text[], 'approved'),
  ('https://www.centrepompidou.fr/fileadmin/_processed_/4/8/csm_dossier_architecture-centre-pompidou_visibilite-4-3-vert_9232b31ead.jpg', 'https://www.centrepompidou.fr/fr/offre-aux-professionnels/enseignants/dossiers-ressources-sur-lart/larchitecture-du-centre-pompidou/image-et-identite', 'Renzo Piano + Richard Rogers  —  Centre Pompidou Paris, Le vert pour l''eau', array['france', 'piano-renzo', 'pipes', 'paris', 'museum', 'green', 'metal', 'ich-war-da', 'concept', 'facade', 'building-services', 'structure', 'green', 'rogers-richard']::text[], 'approved'),
  ('https://www.centrepompidou.fr/fileadmin/_processed_/5/4/csm_dossier_architecture-centre-pompidou_visibilite-4-3-bleu_8c0f4b9d8e.jpg', 'https://www.centrepompidou.fr/fr/offre-aux-professionnels/enseignants/dossiers-ressources-sur-lart/larchitecture-du-centre-pompidou/image-et-identite', 'Renzo Piano + Richard Rogers  —  Centre Pompidou Paris, Le bleu pour l''air', array['france', 'piano-renzo', 'pipes', 'paris', 'museum', 'metal', 'ich-war-da', 'roof', 'blue', 'concept', 'building-services', 'rogers-richard']::text[], 'approved'),
  ('https://www.centrepompidou.fr/fileadmin/_processed_/4/9/csm_dossier_architecture-centre-pompidou_visibilite-2_1ec908840a.jpg', 'https://www.centrepompidou.fr/fr/offre-aux-professionnels/enseignants/dossiers-ressources-sur-lart/larchitecture-du-centre-pompidou/image-et-identite', 'Renzo Piano + Richard Rogers  —  Centre Pompidou Paris', array['france', 'circulation', 'piano-renzo', 'paris', 'museum', 'facade', 'structure', 'escalator', 'glass', 'metal', 'ich-war-da', 'rogers-richard']::text[], 'approved'),
  ('https://www.centrepompidou.fr/fileadmin/_processed_/5/e/csm_dossier_architecture-centre-pompidou_visibilite-4.3.02_7e6fbee897.jpg', 'https://www.centrepompidou.fr/fr/offre-aux-professionnels/enseignants/dossiers-ressources-sur-lart/larchitecture-du-centre-pompidou/image-et-identite', 'Renzo Piano + Richard Rogers  —  Centre Pompidou Paris', array['france', 'circulation', 'colorful', 'pipes', 'piano-renzo', 'paris', 'museum', 'facade', 'structure', 'rogers-richard', 'building-services']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1696591627/fee87518-ee62-46ea-91af-6351519227a8/r-architecture-maxime-delvaux-stephane-chalmeau-p-r-car-park.jpg', 'https://divisare.com/projects/487677-r-architecture-maxime-delvaux-stephane-chalmeau-p-r-car-park', 'R Architecture  —  Parking Vertou', array['france', 'parking', 'ramp', 'concrete', 'circulation', 'roof', 'circular', 'r-architecture']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1696591605/90c543f8-67d1-424c-acea-5768520e97ce/r-architecture-maxime-delvaux-stephane-chalmeau-p-r-car-park.jpg', 'https://divisare.com/projects/487677-r-architecture-maxime-delvaux-stephane-chalmeau-p-r-car-park', 'R Architecture  —  Parking Vertou', array['france', 'parking', 'ramp', 'concrete', 'circulation', 'structure', 'columns', 'r-architecture', 'slabs']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1696591603/ddb77ab7-fa19-4e3c-b9ba-74fb7393bba1/r-architecture-maxime-delvaux-stephane-chalmeau-p-r-car-park.jpg', 'https://divisare.com/projects/487677-r-architecture-maxime-delvaux-stephane-chalmeau-p-r-car-park', 'R Architecture  —  Parking Vertou', array['france', 'parking', 'ramp', 'concrete', 'circular', 'white', 'circulation', 'r-architecture']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1696591606/a8858608-d424-429d-afd1-2dcdce1aecf4/r-architecture-maxime-delvaux-stephane-chalmeau-p-r-car-park.jpg', 'https://divisare.com/projects/487677-r-architecture-maxime-delvaux-stephane-chalmeau-p-r-car-park', 'R Architecture  —  Parking Vertou', array['france', 'parking', 'facade', 'columns', 'r-architecture', 'net', 'tensioned', 'membran']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1607005236/jxin3f5ldrf8bvejcnzc/bruther-baukunst-filip-dujardin-maxime-delvaux-student-residence-and-reversible-car-park.jpg', 'https://divisare.com/projects/434105-bruther-baukunst-filip-dujardin-maxime-delvaux-student-residence-and-reversible-car-park', 'Bruther + Baukunst  —  Reversible Car Park Paris', array['paris', 'france', 'metal', 'bruther', 'baukunst', 'parking', 'lampe']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1607005233/s8gjxgrg7dcrogd5bdg9/bruther-baukunst-filip-dujardin-maxime-delvaux-student-residence-and-reversible-car-park.jpg', 'https://divisare.com/projects/434105-bruther-baukunst-filip-dujardin-maxime-delvaux-student-residence-and-reversible-car-park', 'Bruther + Baukunst  —  Reversible Car Park Paris', array['paris', 'france', 'facade', 'glass', 'concrete', 'ramp', 'bruther', 'baukunst', 'student-housing', 'parking']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1607005228/erphfd3uzbagyvhwj9e9/bruther-baukunst-filip-dujardin-maxime-delvaux-student-residence-and-reversible-car-park.jpg', 'https://divisare.com/projects/434105-bruther-baukunst-filip-dujardin-maxime-delvaux-student-residence-and-reversible-car-park', 'Bruther + Baukunst  —  Reversible Car Park Paris', array['paris', 'france', 'concrete', 'spiral-stair', 'stair', 'bruther', 'baukunst']::text[], 'approved'),
  ('https://www.enzmannfischer.ch/wp-content/uploads/2016/01/243_WGZ_HP_01_FO_Au_ALa_27.jpg', 'https://divisare.com/projects/448724-enzmann-fischer-partner-ag-annett-landsmann-zollhaus', 'Enzmann Fischer Partner  —  Zollhaus Zürich', array['switzerland', 'in-noisy-places', 'zurich', 'enzmann-fischer-partner', 'bar']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1633619723/grjkr7fhzg4c0iishz8r/enzmann-fischer-partner-ag-annett-landsmann-zollhaus.jpg', 'https://divisare.com/projects/448724-enzmann-fischer-partner-ag-annett-landsmann-zollhaus', 'Enzmann Fischer Partner  —  Zollhaus Zürich', array['switzerland', 'zurich', 'enzmann-fischer-partner', 'chain-link-fence', 'staircase']::text[], 'approved'),
  ('https://www.enzmannfischer.ch/wp-content/uploads/2016/01/243_WGZ_HP_01_FO_Au_ALa_21.jpg', null, 'https://www.enzmannfischer.ch/projekt/zollhaus/', array['switzerland', 'enzmann-fischer-partner', 'alternative-living', 'hall']::text[], 'approved'),
  ('images/Enzmann-Fischer-Partner_Zollhaus-Zuerich_halle.jpeg', 'https://divisare.com/projects/448724-enzmann-fischer-partner-ag-annett-landsmann-zollhaus', 'Enzmann Fischer Partner  —  Zollhaus Zürich', array['switzerland', 'zurich', 'enzmann-fischer-partner', 'hall', 'mixed-use', 'stair', 'gallery']::text[], 'approved'),
  ('https://architekturpreis.ch/wp-content/uploads/2024/11/architekturpreis-xif7af.jpg', 'https://architekturpreis.ch/archiv/2022/zollhaus-zuerich-2/', 'Enzmann Fischer Partner  —  Zollhaus Zürich', array['switzerland', 'courtyard', 'housing', 'social-housing', 'facade', 'laubengang', 'enzmann-fischer-partner', 'zurich']::text[], 'approved'),
  ('https://architekturpreis.ch/wp-content/uploads/2024/11/architekturpreis-43ebil.jpg', 'https://architekturpreis.ch/archiv/2022/zollhaus-zuerich-2/', 'Enzmann Fischer Partner  —  Zollhaus Zürich', array['switzerland', 'enzmann-fischer-partner', 'zurich', 'stair', 'columns']::text[], 'approved'),
  ('https://www.enzmannfischer.ch/wp-content/uploads/2016/01/243_WGZ_HP_01_FO_Au_ALa_08-1694x2400.jpg', 'https://www.enzmannfischer.ch/projekt/zollhaus/', 'Enzmann Fischer Partner  —  Zollhaus Zürich', array['switzerland', 'concrete', 'metal', 'facade', 'enzmann-fischer-partner', 'zurich', 'bar']::text[], 'approved'),
  ('https://www.enzmannfischer.ch/wp-content/uploads/2016/01/243_WGZ_HP_GIF_compressed.gif', 'https://www.enzmannfischer.ch/projekt/zollhaus/', 'Enzmann Fischer Partner  —  Zollhaus Zürich', array['switzerland', 'concrete', 'glass-bricks', 'metal', 'hall', 'enzmann-fischer-partner', 'zurich', 'bar']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1633619683/rt5yjnyuw0roja5m3duc/enzmann-fischer-partner-ag-annett-landsmann-zollhaus.jpg', 'https://divisare.com/projects/448724-enzmann-fischer-partner-ag-annett-landsmann-zollhaus', 'Enzmann Fischer Partner  —  Zollhaus Zürich', array['switzerland', 'in-noisy-places', 'corrugated-something', 'concrete', 'metal', 'housing', 'social-housing', 'facade', 'enzmann-fischer-partner', 'zurich', 'mixed-use']::text[], 'approved'),
  ('https://architekturpreis.ch/wp-content/uploads/formidable/2/05_247_BBarc_AuszeichnngKtZH_Paola_Corsini_04.jpg', 'https://architekturpreis.ch/wohnsiedlung-roetiboden-waedenswil/', 'Buchner Bründler  —  Wohnsiedlung Rötiboden Wädenswil', array['switzerland', 'housing', 'spiral-stair', 'concrete', 'interior', 'buchner-bruendler', 'orange']::text[], 'approved'),
  ('https://architekturpreis.ch/wp-content/uploads/formidable/2/04_247_BBarc_AuszeichnngKtZH_Paola_Corsini_29.jpg', 'https://architekturpreis.ch/wohnsiedlung-roetiboden-waedenswil/', 'Buchner Bründler  —  Wohnsiedlung Rötiboden Wädenswil', array['switzerland', 'green', 'colorful', 'housing', 'spiral-stair', 'concrete', 'buchner-bruendler']::text[], 'approved'),
  ('https://architekturpreis.ch/wp-content/uploads/formidable/2/02_247_BBarc_AuszeichnngKtZH_Rory_Gardiner_01-2.jpg', 'https://architekturpreis.ch/wohnsiedlung-roetiboden-waedenswil/', 'Buchner Bründler  —  Wohnsiedlung Rötiboden Wädenswil', array['switzerland', 'housing', 'colorful', 'balcony', 'facade', 'spiral-stair', 'concrete', 'buchner-bruendler']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1663833319/nwvx0yoqjct6pwu2dfra/buchner-brundler-architekten-rory-gardiner-cooperative-building-stadterle.jpg', 'https://divisare.com/projects/466673-buchner-brundler-architekten-rory-gardiner-cooperative-building-stadterle', 'Buchner Bründler  —  Stadterle Basel', array['basel', 'ich-war-da', 'circulation', 'buchner-bruendler', 'stair', 'handrail', 'metal']::text[], 'approved'),
  ('https://www.buildingsocialecology.org/wp-content/uploads/2022/07/stadterle-basel-private-apartment-daisuke-hirabayashi.jpeg', 'https://www.buildingsocialecology.org/projekte/stadterle-deutsch/', 'Buchner Bründler  —  Stadterle Basel', array['basel', 'ich-war-da', 'apartment-interior', 'wood', 'concrete', 'buchner-bruendler']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1663833316/k6svpubcvsf38fzhnfrv/buchner-brundler-architekten-rory-gardiner-cooperative-building-stadterle.jpg', 'https://divisare.com/projects/466673-buchner-brundler-architekten-rory-gardiner-cooperative-building-stadterle', 'Buchner Bründler  —  Stadterle Basel', array['basel', 'housing', 'corrugated-something', 'switzerland', 'social-housing', 'balcony', 'facade', 'ich-war-da', 'green', 'circulation', 'buchner-bruendler', 'laubengang']::text[], 'approved'),
  ('http://hiddenarchitecture.net/wp-content/uploads/2018/06/01-2-1024x844.jpg', 'https://hiddenarchitecture.net/two-single-family-houses/', 'Peter Märkli — Two Houses, Trübbach', array['maerkli-peter', 'switzerland', 'mountains', 'house', 'plaster', 'cubic']::text[], 'approved'),
  ('https://www.sauerbruchhutton.de/cache/images/media/projekte/gsw/2567-avif@75-gsw_hero-c.jpg.avif', 'https://www.sauerbruchhutton.de/de/project/gsw', 'Sauerbruch Hutton  —  GSW Headquarters Berlin', array['facade', 'glass', 'colorful', 'sauerbruch-hutton', 'germany', 'berlin', 'office', 'contemporary']::text[], 'approved'),
  ('https://www.sauerbruchhutton.de/cache/images/media/projekte/gsw/1600-avif%4075-gsw_annettekisling_616.jpg.avif', 'https://www.sauerbruchhutton.de/de/project/gsw', 'Sauerbruch Hutton  —  GSW Headquarters Berlin', array['facade', 'glass', 'colorful', 'sauerbruch-hutton', 'germany', 'berlin', 'office', 'contemporary']::text[], 'approved'),
  ('http://www.archipicture.eu/2%20Bilder/Schweiz/Olgiati%20Valerio/Valerio%20Olgiati%20-%20GrisonsParliamentEntrance%206sm.jpg', 'http://www.archipicture.eu/Architekten/Schweiz/Olgiati%20Valerio/Valerio%20Olgiati%20-%20GrisonsParliamentEntrance%206.html', 'Valerio Olgiati  —  Vordach Chur', array['switzerland', 'concrete', 'ich-war-da', 'white', 'ramp', 'stair', 'olgiati-valerio', 'porch']::text[], 'approved'),
  ('https://64.media.tumblr.com/6ca20f37e50575348dbe479c1531ef3a/tumblr_n67521BBLU1qat99uo4_500.jpg', 'https://www.subtilitas.site/post/86923458854/valerio-olgiati-new-entrance-to-the', 'Valerio Olgiati  —  Vordach Chur', array['switzerland', 'concrete', 'ich-war-da', 'white', 'handrail', 'metal', 'olgiati-valerio', 'porch']::text[], 'approved'),
  ('https://journals.openedition.org/lha/docannexe/image/4916/img-1-small480.jpg', 'https://journals.openedition.org/lha/4916', 'Le Corbusier — Cabanon', array['le-corbusier', 'cabin', 'france', 'coast', 'wood', 'house']::text[], 'approved'),
  ('https://journals.openedition.org/lha/docannexe/image/4916/img-5-small480.jpg', 'https://journals.openedition.org/lha/4916', 'Le Corbusier — Cabanon', array['le-corbusier', 'cabin', 'france', 'wood', 'house', 'bathroom', 'metal', 'sink']::text[], 'approved'),
  ('https://www.fondationlecorbusier.fr/wp-content/uploads/2022/04/le-corbusier-le-cabanon-2-flc-adagp-manuel-bougot.jpg', 'https://www.fondationlecorbusier.fr/oeuvre-architecture/realisations-cabanon-de-le-corbusier-roquebrune-cap-martin-france-1951/e', 'Le Corbusier — Cabanon', array['le-corbusier', 'cabin', 'colorful', 'france', 'wood', 'house', 'interior']::text[], 'approved'),
  ('http://www.danmarks-kirker.dk/viborg/holstebro/kirke_foto/norrelands_hols_001.jpg', 'http://www.danmarks-kirker.dk/viborg/holstebro/norrelands_hols.htm', 'Inger Exner + Johannes Exner  —  Nørrelandskirken Holstebro', array['stair', 'structure', 'denmark', 'spiral-stair', 'tower', 'exner-inger-johannes', 'church']::text[], 'approved'),
  ('http://www.danmarks-kirker.dk/viborg/holstebro/kirke_foto/norrelands_hols_011.jpg', 'http://www.danmarks-kirker.dk/viborg/holstebro/norrelands_hols.htm', 'Inger Exner + Johannes Exner  —  Nørrelandskirken Holstebro', array['stair', 'lamp', 'denmark', 'exner-inger-johannes', 'church']::text[], 'approved'),
  ('http://socks-studio.com/img/blog/vaccaro-asilo-piacenza-03.jpg', 'https://socks-studio.com/2017/03/07/a-though-exercise-in-simplicity-vaccaros-kindergarten-in-piacenza/', 'Vaccaro Giuseppe — Kindergarten, Piacenza', array['kindergarten', 'concrete', 'italy', 'circular', 'pavilion', 'courtyard', 'vaccaro-giuseppe']::text[], 'approved'),
  ('https://images.divisare.com//images/f_auto,q_auto,w_800/v1517995670/osw9fnwjoaxsdg6rmd34/de-vylder-vinck-taillieu-jo-taillieu-jan-de-vylder-inge-vinck-filip-dujardin-podium-pile-pavilion.jpg', 'https://divisare.com/projects/379017-de-vylder-vinck-taillieu-jo-taillieu-jan-de-vylder-inge-vinck-filip-dujardin-podium-pile-pavilion', 'De Vylder Vinck Taillieu — Podium-Pile-Pavilion', array['belgium', 'pavilion', 'de-vylder-vinck-taillieu', 'concrete', 'brick', 'columns']::text[], 'approved'),
  ('https://static.dezeen.com/uploads/2022/04/parc-de-villette-bernard-tschumi-deconstructivism_dezeen_2364_hero_6.jpg', 'https://www.dezeen.com/2022/05/05/parc-de-la-villette-deconstructivism-bernard-tschumi/', 'Bernard Tschumi — Parc de la Villette', array['tschumi-bernard', 'ich-war-da', 'france', 'paris', 'pavilion', 'metal', 'red', 'park']::text[], 'approved'),
  ('https://www.udg.org.uk/sites/default/files/styles/900x/public/articles/images/Parc-De-La-Villette-High-Res-Plan.jpg?itok=uOh7Fdzb', 'https://www.udg.org.uk/publications/articles/parc-de-la-villette-paris', 'Bernard Tschumi — Parc de la Villette', array['tschumi-bernard', 'france', 'ich-war-da', 'paris', 'pavilion', 'metal', 'red', 'park', 'concept', 'representation']::text[], 'approved'),
  ('https://arquitecturaviva.com/assets/uploads/obras/46031/av_imagen.webp?h=5ed314d8', 'https://arquitecturaviva.com/works/museo-de-la-fundacion-beyeler-riehen-9', 'Renzo Piano — Fondation Beyeler', array['piano-renzo', 'ich-war-da', 'basel', 'switzerland', 'museum', 'glass', 'stone']::text[], 'approved'),
  ('https://arquitecturaviva.com/assets/uploads/obras/40919/av_medium__av_83620.webp?h=0bb97f92', 'https://arquitecturaviva.com/works/fundacion-jerome-seydoux-pathe-4', 'Renzo Piano — Pathé Foundation', array['piano-renzo', 'ich-war-da', 'paris', 'france', 'glass', 'roof', 'organic', 'metal', 'facade']::text[], 'approved'),
  ('https://old.skyscraper.org/EXHIBITIONS/VERTICAL_URBAN_FACTORY/walkthrough_images/lingotto_web.jpg', 'https://old.skyscraper.org/EXHIBITIONS/VERTICAL_URBAN_FACTORY/fiat.php', 'Giacomo Matté-Trucco — Fiat Lingotto', array['matte-trucco', 'ich-war-da', 'turin', 'italy', 'concrete', 'factory', 'roof', 'industrial', 'ramp', 'circulation', 'metal', 'facade']::text[], 'approved'),
  ('https://64.media.tumblr.com/3543ffc5a130f579f265ff9ae8ce8f7a/tumblr_p8ues7obCy1udgrilo1_500.jpg', 'https://architectureandfilm.com/post/174088772131/fiat-lingotto-factory-turin-matté-trucco-1923', 'Giacomo Matté-Trucco — Fiat Lingotto', array['matte-trucco', 'ich-war-da', 'turin', 'italy', 'concrete', 'factory', 'industrial', 'structure', 'ramp', 'circulation', 'metal']::text[], 'approved'),
  ('https://publicdelivery.org/wp-content/uploads/2020/01/Gordon-Matta-Clark-Conical-Intersect-1975-2-800x1219.jpg', 'https://publicdelivery.org/matta-clark-conical-intersect/', 'Gordon Matta-Clark — Conical Intersect', array['paris', 'gta', 'facade', 'matta-clark-gordon', 'representation']::text[], 'approved'),
  ('https://christophehutin.com/media/pages/projets/transformation-de-530-logements-batiments-gh-et-i-du-grand-parc/ac02f03b6b-1689179563/hutin-lacaton-vassal-druot-bordeaux-logement13-2480x-q90.jpg', 'https://christophehutin.com/en/projects/transformation-de-530-logements-batiments-gh-et-i-du-grand-parc', 'Lacaton & Vassal, Druot, Hutin — Transformation 530 logements, Bordeaux', array['bordeaux', 'lacaton-vassal', 'transformation', 'france', 'housing', 'social-housing', 'facade', 'extension', 'glass', 'balcony']::text[], 'approved'),
  ('https://christophehutin.com/media/pages/projets/transformation-de-530-logements-batiments-gh-et-i-du-grand-parc/b08d180ab0-1689179555/hutin-lacaton-vassal-druot-bordeaux-logement10-2480x-q90.jpg', 'https://christophehutin.com/en/projects/transformation-de-530-logements-batiments-gh-et-i-du-grand-parc', 'Lacaton & Vassal, Druot, Hutin — Transformation 530 logements, Bordeaux', array['bordeaux', 'lacaton-vassal', 'transformation', 'france', 'housing', 'social-housing', 'facade', 'extension', 'glass', 'balcony']::text[], 'approved')
on conflict (image, (coalesce(source, '')), title) do nothing;

commit;
